FROM node:20-alpine

WORKDIR /app

# Installer les dépendances
COPY package*.json ./
RUN npm ci

# Copier tout le code source
COPY . .

# Exposer les ports pour Vite et Express
EXPOSE 5173 5174

# Commande pour lancer le serveur de développement
CMD ["npm", "run", "dev"]

